export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Home } from './Home/Home'
export { default as Projects } from './Projects/Projects'
export { default as Site } from './Site/Site'
export { default as ProjectDetails } from './ProjectDetails/ProjectDetails'
export { default as ProfilePicture } from './ProfilePicture/ProfilePicture'